In [27]:
import numpy as np

# X = (hours sleeping, hours studying), y = score on test
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

# scale units
X = X/np.amax(X, axis=0) # maximum of X array
y = y/100 # max test score is 100

In [28]:
#input, hidden, and output layers.

class Neural_Network(object):
  def __init__(self):
    #parameters
    self.inputSize = 2
    self.outputSize = 1
    self.hiddenSize = 3

In [50]:
import numpy as np

# X = (hours sleeping, hours studying), y = score on test
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

# scale units
X = X/np.amax(X, axis=0) # maximum of X array
y = y/100 # max test score is 100

class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3) # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1/(1+np.exp(-s))
    
    def predict(self):
        print ("Predicted data based on trained weights: ")
        print ("Input (scaled): \n" + str(xPredicted))
        print ("Output: \n" + str(self.forward(xPredicted)))

NN = Neural_Network()

#defining our output
o = NN.forward(X)

print ("Predicted Output: \n", str(o))
print ("Actual Output: \n", str(y))
print()

xPredicted = np.array(([4,8]), dtype=float)
xPredicted = xPredicted/np.amax(xPredicted, axis=0) # maximum of xPredicted (our input data for the prediction)

NN.predict()

Predicted Output: 
 [[ 0.85980055]
 [ 0.83083027]
 [ 0.84624902]]
Actual Output: 
 [[ 0.92]
 [ 0.86]
 [ 0.89]]

Predicted data based on trained weights: 
Input (scaled): 
[ 0.5  1. ]
Output: 
[ 0.8585589]


In [56]:
import numpy as np

# X = (hours studying, hours sleeping), y = score on test, xPredicted = 4 hours studying & 8 hours sleeping (input data for prediction)
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
xPredicted = np.array(([4,8]), dtype=float)

# scale units
X = X/np.amax(X, axis=0) # maximum of X array
xPredicted = xPredicted/np.amax(xPredicted, axis=0) 
# maximum of xPredicted (our input data for the prediction)
y = y/100 # max test score is 100

print("X=", X)
print("Y=", y)
print("xPredicted=", xPredicted)
print()

class Neural_Network(object):
    def __init__(self):      #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
#weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) 
    # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) 
    # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = np.dot(self.z2, self.W2) 
        # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3) # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1/(1+np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propagate through the network
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.W2.T) 
        # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) 
        # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def predict(self):
        print ("Predicted data based on trained weights: ");
        print ("Input (scaled): \n" + str(xPredicted));
        print ("Output: \n" + str(self.forward(xPredicted)));

NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
    print ("# " + str(i) + "\n")
    print ("Input (scaled): \n" + str(X))
    print ("Actual Output: \n" + str(y))
    print ("Predicted Output: \n" + str(NN.forward(X)))
    print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) 
    print ("\n")
    NN.train(X, y)

NN.predict()

X= [[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Y= [[ 0.92]
 [ 0.86]
 [ 0.89]]
xPredicted= [ 0.5  1. ]

# 0

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.66771597]
 [ 0.59280601]
 [ 0.63985847]]
Loss: 
0.0658702159802


# 1

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.71833743]
 [ 0.64320224]
 [ 0.69343382]]
Loss: 
0.0421024412612


# 2

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.75244796]
 [ 0.6785581 ]
 [ 0.72978165]]
Loss: 
0.0288882568559


# 3

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89