## NumPy Array Manipulation 

### concatenate()

In [1]:
import numpy as np 

a = np.array([[1,2],[3,4]]) 
print('First array:') 
print(a)

b = np.array([[5,6],[7,8]]) 
print('Second array:') 
print(b)

# both the arrays are of same dimensions 

print('Joining the two arrays along axis 0:') 
print(np.concatenate((a,b))) 

print('Joining the two arrays along axis 1:') 
print(np.concatenate((a,b),axis = 1))

First array:
[[1 2]
 [3 4]]
Second array:
[[5 6]
 [7 8]]
Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


### arrange()
np.arange(start, stop, step) - (interval including start, but excluding stop).

In [2]:
np.arange(3)

array([0, 1, 2])

In [3]:
np.arange(3.0)

array([0., 1., 2.])

In [4]:
np.arange(3,7)

array([3, 4, 5, 6])

In [5]:
np.arange(3,7,2)

array([3, 5])

### reshape()

##### This function gives a new shape to an array without changing the data.
numpy.reshape(arr, newshape, order)

In [6]:
import numpy as np
a = np.arange(8)
print('The original array:', a)
#print a

b = a.reshape(4,2)
print('The modified array:')
print(b)

The original array: [0 1 2 3 4 5 6 7]
The modified array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


## meshgrid()
A Meshgrid is an ND-coordinate space generated by a set of arrays. Each point on the meshgrid corresponds to a combination of one value from each of the arrays.

#### If you give np.meshgrid() two 1D arrays Array A and Array B such that <br/>
A is [a1,a2,a3]
and B is [b1,b2,b3],
<br/>then running <b>np.meshgrid(A, B)</b> returns a list of two 2D arrays, which look like

[[a1,a1,a1],[a2,a2,a2],[a3,a3,a3]]
and

[[b1,b1,b1],[b2,b2,b2],[b3,b3,b3]]
<br/>for which each array here contains arrays with an array full of the first item, the next filled with all the next item in the original array, etc.<br/>
By adding these two arrays together, we can create the 2D array containing, as its elements, every combination of sums between the numbers in the original elements.

In [11]:
# declaring how many x and y points we want (3 and 2)
nx, ny = (3, 2)

# create a linear space with 3 points between 0 and 1 inclusive
x = np.linspace(0, 1, nx)
print(x)

[0.  0.5 1. ]


In [13]:
# create a linear space with 2 points between 0 and 1 inclusive
y = np.linspace(0, 1, ny)
print(y)

[0. 1.]


In [17]:
# Using the meshgrid function, which takes two or more vectors.
# It meshes the vectors together to get a grid. In this case,
# meshing x and y creates a Cartesian plane
xv, yv = np.meshgrid(x, y)
print(xv)
print(yv)

[[0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0. 0. 0.]
 [1. 1. 1.]]


In [18]:
# xv and yv are now kind of "meshed" versions of the original x, y.
# If you combine xv and yv into coordinates, you'll get:
# (0, 0), (0.5, 0), (1, 0)
# (0, 1), (0.5, 1), (1, 1)
# For every point in x, there are all the y points and vice versa.