### Import necessary Libraries.

numpy: for scientific computing

sklearn: provides simlpe and efficient tools for data analysis

pandas: provides fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive

matplotlib: plotting library for the Python programming language and its numerical mathematics extension NumPy

In [1]:
import numpy as np
from sklearn import datasets

import pandas as pd
from pandas import DataFrame as df

import matplotlib.pyplot as plt

### Loading of the Iris dataset


In [2]:
#Load iris dataset

iris = datasets.load_iris()
X = iris.data
Y = iris.target

#Combining features and target to see the whole data altogether.

X = np.insert(X, X.shape[1], Y,  axis=1)
data = pd.DataFrame(X)

data = data.reindex(np.random.permutation(data.index))
data.head()

0    1    2    3    4
55   5.7  2.8  4.5  1.3  1.0
81   5.5  2.4  3.7  1.0  1.0
53   5.5  2.3  4.0  1.3  1.0
120  6.9  3.2  5.7  2.3  2.0
117  7.7  3.8  6.7  2.2  2.0

### Assignig Class Labels and viewing the target class

In [4]:
features = data.iloc[:,:4]
target = data.iloc[:,4]

target = target.values.reshape((target.shape[0],1)) # Reshaping target for matrix multiplication
target_class = np.zeros(shape=(target.shape[0],3))  # Initializing class labels as [0,0,0]

# Assigning class labels as [1,0,0], [0,1,0] and [0,0,1]

for i in range(target.shape[0]):
    if target[i] == 0:
        target_class[i][0] = 1
    elif target[i]==1:
        target_class[i][1] = 1
    else:
        target_class[i][2] = 1

print(target_class.shape)
print('\n')
print(target_class)

(150, 3)


[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 

### Definition of the Sigmoid Activation function

In [5]:
#Defining activation function (here sigmoid)

def sigmoid(x):
    return 1/(1+np.exp(-x))

#Defining derivative of sigmoid function

def der_sigmoid(x):
    return(sigmoid(x)*(1-sigmoid(x)))


### Defining the layer-wise node-count of the Single Layer NN

In [6]:
input_nodes = features.shape[1]
output_nodes = 3

#Initializing weight matrix of size input_nodes x output_nodes with random values.
weight_matrix = np.random.uniform(size=(input_nodes, output_nodes))

#Assigning epoch and learning rate value.
epoch = 1000
lr = 0.005

### Weight Updation

In [7]:
#Updating weights

for i in range(epoch):
    output_node_input = features.dot(weight_matrix)
    output = sigmoid(output_node_input)
    
    error = target_class - output
    drv = der_sigmoid(output_node_input)
    delta_weight = error*drv
    
    weight_matrix = weight_matrix + lr*features.T.dot(delta_weight)
    

### Making the Predictions

In [19]:
final_output = np.array(output)
print('Final Output:\n')
print(final_output, '\n')

output_class = np.zeros(shape=final_output.shape[0])

for i in range(final_output.shape[0]):
    output_class[i] = np.argmax(final_output[i])

#print('Output_class:\n') This has been done in the next cell for better understandability
#print(output_class)

class_diff = output_class - target[:,0]

Final Output:

[[1.33888049e-02 4.36149955e-01 2.90177906e-01]
 [3.81506639e-02 6.29403722e-01 5.42423830e-02]
 [1.55070798e-02 5.81273709e-01 2.92593975e-01]
 [1.74455597e-03 2.50972769e-01 9.08145422e-01]
 [7.04098225e-04 2.88966540e-01 8.67917093e-01]
 [9.79620008e-01 9.27318491e-02 3.66783169e-06]
 [1.16976625e-03 5.48240168e-01 7.10324911e-01]
 [4.23546448e-02 2.86529592e-01 1.01969908e-01]
 [6.32515007e-03 3.77201431e-01 6.15199305e-01]
 [3.48805407e-02 1.59841332e-01 1.49707987e-01]
 [9.33627891e-01 2.66767953e-01 1.54231418e-05]
 [1.73144465e-02 2.50156583e-01 3.92741390e-01]
 [1.12953542e-03 2.47292133e-01 9.54949885e-01]
 [9.74585996e-01 2.17084268e-01 2.13595691e-06]
 [1.69275959e-03 2.12510453e-01 9.50203665e-01]
 [2.52477192e-03 3.51756247e-01 8.01770091e-01]
 [7.49256064e-03 7.84131423e-01 1.87670025e-01]
 [1.57317245e-02 4.71734122e-01 8.34453761e-02]
 [2.18929628e-02 4.83389070e-01 2.19122790e-01]
 [1.12129465e-02 5.59232767e-01 1.58573739e-01]
 [9.62507712e-02 2.857355

### Comparison of Training Examples with Predicted Results

In [20]:
print('Actual Class')
print(target[:,0])

print("\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n")

print('Predicted Class')
print(output_class)

wrong_prediction = np.count_nonzero(class_diff)

N = len(class_diff)

simple_accuracy = 100 * (N-wrong_prediction)/N
print("\nAccuracy : ",(simple_accuracy) ,'%')

Actual Class
[1. 1. 1. 2. 2. 0. 2. 1. 2. 1. 0. 1. 2. 0. 2. 2. 1. 1. 1. 1. 1. 0. 2. 1.
 2. 2. 0. 2. 2. 0. 0. 2. 2. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 2.
 1. 2. 1. 2. 1. 2. 0. 1. 0. 2. 1. 2. 0. 2. 0. 0. 0. 2. 2. 0. 1. 1. 0. 0.
 1. 1. 0. 0. 2. 1. 1. 0. 2. 1. 0. 0. 1. 2. 1. 0. 2. 0. 0. 1. 2. 2. 1. 1.
 0. 2. 1. 0. 0. 1. 0. 1. 0. 0. 2. 2. 1. 2. 2. 2. 1. 1. 1. 2. 2. 2. 2. 1.
 0. 2. 0. 2. 1. 1. 2. 1. 2. 2. 0. 1. 0. 2. 2. 0. 2. 0. 1. 2. 0. 2. 0. 2.
 1. 1. 0. 0. 0. 0.]

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Predicted Class
[1. 1. 1. 2. 2. 0. 2. 1. 2. 1. 0. 2. 2. 0. 2. 2. 1. 1. 1. 1. 1. 0. 2. 1.
 2. 2. 0. 2. 2. 0. 0. 2. 2. 1. 1. 1. 2. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 2.
 1. 2. 1. 2. 1. 2. 0. 1. 0. 2. 2. 2. 0. 2. 0. 0. 0. 2. 2. 0. 1. 1. 0. 0.
 1. 1. 0. 0. 2. 1. 1. 0. 2. 1. 0. 0. 1. 2. 1. 0. 1. 0. 0. 1. 2. 2. 1. 1.
 0. 2. 1. 0. 0. 1. 0. 1. 0. 0. 2. 2. 1. 2. 2. 2. 1. 1. 1. 2. 2. 2. 2. 1.
 0. 2. 0. 1. 1. 1. 2. 1. 2. 2. 0. 1. 0. 2. 2. 0. 2. 0. 2. 2. 0. 2. 0. 2.
 1. 1. 0. 0. 0. 0.]

Accuracy :  

### There you have it! 

### An actual single-layer NN to predict classes from the Iris Dataset!